import {it,expect,vi,afterEach} from 'vitest';
import {applySync} from '../../../src/lib/applySync';
import type {TimelineProject,AudioSource} from '../../../src/types/audio';
const alignment={offset:.1,rate:1.001,confidence:.9,residual_ms:1,reliable:true,manual:false,anchors:[]};
function fixture(){const segment={id:'a',sourceId:'s',trackId:'t',startTime:.2,sourceOffset:0,duration:1,fadeInDuration:0,fadeOutDuration:0,fadeInCurve:'linear' as const,fadeOutCurve:'linear' as const,effects:[],gain:1,color:'blue',name:'a'};const project:TimelineProject={id:'p',name:'p',sampleRate:1000,duration:1.2,tracks:[{id:'t',name:'t',muted:false,solo:false,pan:0,volume:1,segments:[segment]}],masterEffects:[]};const data=new Float32Array(1000).map((_,i)=>i/1000),source={id:'s',name:'s',duration:1,sampleRate:1000,channels:1,buffer:{length:1000,getChannelData:()=>data},peaks:{min:new Float32Array(),max:new Float32Array()}} as unknown as AudioSource;return {project,sources:new Map([['s',source]])};}
afterEach(()=>vi.unstubAllGlobals());
it('records offset decisions and retains original audio sources',async()=>{const f=fixture(),next=await applySync(f.project,f.sources,'reference',[{id:'t',alignment}],false);expect(next.project.tracks[0].segments[0].startTime).toBeCloseTo(.1);expect(next.sources.get('s')).toBe(f.sources.get('s'));expect(next.project.syncHistory?.[0].tracks[0].alignment.rate).toBe(1.001);expect(f.project.tracks[0].segments[0].startTime).toBe(.2);});
it('creates corrected sources with the inverse timeline clock mapping',async()=>{vi.stubGlobal('AudioBuffer',class{length:number;sampleRate:number;numberOfChannels:number;duration:number;data:Float32Array;constructor(o:{length:number;sampleRate:number;numberOfChannels:number}){Object.assign(this,o);this.length=o.length;this.sampleRate=o.sampleRate;this.numberOfChannels=o.numberOfChannels;this.duration=o.length/o.sampleRate;this.data=new Float32Array(o.length);}getChannelData(){return this.data;}});const f=fixture(),next=await applySync(f.project,f.sources,'reference',[{id:'t',alignment}],true),clip=next.project.tracks[0].segments[0];expect(clip.startTime).toBeCloseTo(.1/1.001);expect(clip.duration).toBeCloseTo(1/1.001);expect(clip.sourceId).not.toBe('s');expect(next.sources.get(clip.sourceId)?.buffer.getChannelData(0)[500]).toBeCloseTo(.5005);expect(next.sources.has('s')).toBe(true);});
it('rejects uncertain results without changing the project',async()=>{const f=fixture();await expect(applySync(f.project,f.sources,'reference',[{id:'t',alignment:{...alignment,reliable:false}}],false)).rejects.toThrow('Uncertain');expect(f.project.syncHistory).toBeUndefined();});
it('does not resample linked picture at a different speed',async()=>{const f=fixture();f.project.tracks[0].segments[0].linkGroup='g';f.project.video={path:'/camera.mp4',duration:2,session:{} as never,clips:[{id:'v',linkGroup:'g',startTime:.2,sourceOffset:0,duration:1,fadeIn:0,fadeOut:0,transition:'cut',transitionDuration:0}]};await expect(applySync(f.project,f.sources,'reference',[{id:'t',alignment}],true)).rejects.toThrow('Unlink picture');});
