import {describe,it,expect} from 'vitest';
import {planKeptText,keepSpokenWords,speechTokens} from '../../../src/lib/keepSpeech';
import {speechLayout} from '../../../src/lib/spokenEdits';
import type {TimelineProject} from '../../../src/types/audio';
function fixture(text='Wir lernen heute und morgen weiter'):TimelineProject {
 const words=text.split(' ').map((text,i)=>({id:`w${i}`,text,start:i+.2,end:i+.7}));const duration=words.length+1;
 const clip={id:'a',trackId:'t',sourceId:'s',linkGroup:'av',startTime:0,duration,sourceOffset:10,gain:1,name:'Mic',color:'#fff',effects:[],fadeInDuration:0,fadeOutDuration:0,fadeInCurve:'linear' as const,fadeOutCurve:'linear' as const};
 const p:TimelineProject={id:'p',name:'Interview',sampleRate:48000,frameRate:25,duration,minimumDuration:duration,masterEffects:[],tracks:[{id:'t',name:'Mic',muted:false,solo:false,volume:1,pan:0,segments:[clip]},{id:'room',name:'Room',muted:false,solo:false,volume:1,pan:0,rippleEnabled:false,segments:[{...clip,id:'b',trackId:'room',linkGroup:undefined}]}],video:{path:'v.mp4',duration:20,session:{} as never,clips:[{id:'v',linkGroup:'av',startTime:0,duration,sourceOffset:10,fadeIn:0,fadeOut:0,transition:'cut',transitionDuration:0}]},markers:[{id:'m',time:4.4,name:'question'}],transcript:[{id:'c',start:words[0].start,end:words.at(-1)!.end,text,words}]};p.transcriptLayout=speechLayout(p);return p;
}
describe('keep a shortened pasted transcript',()=>{
 it('matches case, punctuation, line breaks and German Unicode',()=>{expect(speechTokens('„Äußerst schön!“ E-Mail DON’T')).toEqual(['äußerst','schön','e','mail',"don't"]);const p=fixture();const plan=planKeptText(p,'WIR lernen.\n\nMorgen weiter!');expect(plan.ambiguous).toBe(false);expect(plan.wordIds).toEqual(['w0','w1','w4','w5']);expect(plan.ranges).toHaveLength(2);});
 it('keeps only contiguous matched passages and removes intro/outro plus deleted speech',()=>{const p=fixture(),plan=planKeptText(p,'Wir lernen morgen weiter'),out=keepSpokenWords(p,plan.wordIds);expect(plan.ranges.map(r=>[r.start,r.end])).toEqual([[.2,1.72],[4.2,5.72]]);expect(out.duration).toBeCloseTo(3.04);expect(out.tracks.map(t=>t.segments.map(c=>c.sourceOffset))).toEqual([[10.2,14.2],[10.2,14.2]]);expect(out.video!.clips!.map(c=>c.sourceOffset)).toEqual([10.2,14.2]);expect(out.transcript![0].text).toBe('Wir lernen morgen weiter');expect(out.transcript![0].words![2].start).toBeCloseTo(1.52);expect(out.markers![0].time).toBeCloseTo(1.72);expect(p.duration).toBe(7);expect(out.transcriptLayout).toEqual(speechLayout(out));});
 it('flags repeated phrases and supports exact occurrence pins or earliest/latest review',()=>{const p=fixture('ja gut ja gut ja gut');const a=planKeptText(p,'ja gut');expect(a.ambiguous).toBe(true);expect(a.ambiguity!.candidates.map(c=>c.start)).toEqual([.2,2.2,4.2]);const b=planKeptText(p,'ja gut',{occurrences:{0:2,1:3}});expect(b.ambiguous).toBe(false);expect(b.wordIds).toEqual(['w2','w3']);expect(planKeptText(p,'ja gut',{choice:'latest'}).wordIds).toEqual(['w4','w5']);});
 it('uses surrounding context to disambiguate repetitions',()=>{const p=fixture('ja nein ja gut');expect(planKeptText(p,'nein ja gut').ambiguous).toBe(false);});
 it('rejects empty, inserted, reordered and partially aligned words',()=>{const p=fixture();expect(()=>planKeptText(p,'')).toThrow('empty');expect(()=>planKeptText(p,'Wir erfinden')).toThrow('mismatch');expect(()=>planKeptText(p,'weiter Wir')).toThrow('mismatch');expect(()=>planKeptText(fixture('E-Mail gut'),'Mail gut')).toThrow('partialWord');});
 it('requires complete timing and rejects a moved/slipped arrangement',()=>{const p=fixture();p.tracks[0].segments[0].sourceOffset++;expect(()=>planKeptText(p,'Wir')).toThrow('stale');const q=fixture();q.transcript![0].words=undefined;expect(()=>planKeptText(q,'Wir')).toThrow('untimed');});
 it('enforces locks, adjacent frame speech and atomic failure across multiple deletions',()=>{const p=fixture();p.tracks[1].locked=true;const before=JSON.stringify(p);expect(()=>keepSpokenWords(p,['w0','w4'])).toThrow('locked');expect(JSON.stringify(p)).toBe(before);p.tracks[1].locked=false;p.transcript![0].words![1].start=.71;expect(()=>planKeptText(p,'Wir')).toThrow('neighbour');});
 it('removes a non-frame-aligned trailing canvas without a tiny residual clip',()=>{const p=fixture('Hallo');p.minimumDuration=2.501;p.tracks.forEach(t=>t.segments[0].duration=2.501);p.video!.clips![0].duration=2.501;p.duration=2.501;p.transcriptLayout=speechLayout(p);const out=keepSpokenWords(p,['w0']);expect(out.duration).toBeCloseTo(.52);expect(out.tracks[0].segments).toHaveLength(1);});
 it('lets ambiguity be resolved when an early occurrence is only part of a timed compound word',()=>{const p=fixture('E-Mail Mail');const plan=planKeptText(p,'Mail');expect(plan.ambiguous).toBe(true);expect(planKeptText(p,'Mail',{occurrences:{0:2}}).wordIds).toEqual(['w1']);});
 it('handles long repeated sequences without a quadratic match matrix',()=>{const p=fixture(Array(1000).fill('ja').join(' '));const plan=planKeptText(p,Array(500).fill('ja').join(' '));expect(plan.ambiguous).toBe(true);expect(plan.ambiguity!.candidates).toHaveLength(200);expect(plan.ambiguity!.more).toBe(true);});
});
