import {describe,it,expect} from 'vitest';
import {deleteSpokenWord,speechLayout} from '../../../src/lib/spokenEdits';
import {parseTranscript} from '../../../src/lib/transcript';
import type {TimelineProject} from '../../../src/types/audio';
const fixture=()=>({id:'p',name:'Speech',duration:5,sampleRate:48000,frameRate:25,masterEffects:[],markers:[{id:'m',time:4,name:'Later'}],tracks:[{id:'t',name:'Mic',volume:1,pan:0,muted:false,solo:false,segments:[{id:'a',trackId:'t',sourceId:'s',startTime:0,duration:5,sourceOffset:10,linkGroup:'av',gain:1,effects:[],fadeInDuration:0,fadeOutDuration:0,fadeInCurve:'linear',fadeOutCurve:'linear',name:'Mic',color:'#fff'}]}],video:{path:'v.mp4',duration:20,session:{},clips:[{id:'v',startTime:0,duration:5,sourceOffset:10,linkGroup:'av',fadeIn:0,fadeOut:0,transition:'cut',transitionDuration:0}]},transcript:[{id:'c',start:1,end:3,text:'Wir schneiden Wörter.',words:[{id:'w1',start:1,end:1.4,text:'Wir'},{id:'w2',start:1.5,end:2,text:'schneiden'},{id:'w3',start:2.1,end:3,text:'Wörter.'}]}]} as TimelineProject);
describe('aligned speech edits',()=>{
 it('blocks stale ASR alignment after other audio arrangement edits',()=>{const p=fixture();p.transcriptLayout=speechLayout(p);p.tracks[0].segments[0].sourceOffset+=1;expect(()=>deleteSpokenWord(p,'w2')).toThrow('stale');});
 it('cuts all sound and picture, source offsets, words and later markers atomically',()=>{const p=fixture(),out=deleteSpokenWord(p,'w2');expect(p.duration).toBe(5);expect(out.duration).toBeCloseTo(4.48);const [left,right]=out.tracks[0].segments;expect(left.duration).toBe(1.48);expect(right.startTime).toBe(1.48);expect(right.sourceOffset).toBe(12);expect(out.video!.clips![1].sourceOffset).toBe(12);expect(right.linkGroup).toBe(out.video!.clips![1].linkGroup);expect(out.transcript![0].text).toBe('Wir Wörter.');expect(out.transcript![0].words![1].start).toBeCloseTo(1.58);expect(out.markers![0].time).toBeCloseTo(3.48);});
 it('includes a lane excluded from ordinary ripple edits',()=>{const p=fixture();p.tracks[0].rippleEnabled=false;p.video!.rippleEnabled=false;expect(deleteSpokenWord(p,'w2').video!.clips).toHaveLength(2);});
 it('blocks locked lanes and ambiguous adjacent word rounding',()=>{const p=fixture();p.tracks[0].locked=true;expect(()=>deleteSpokenWord(p,'w2')).toThrow('locked');p.tracks[0].locked=false;p.transcript![0].words![0].end=1.53;expect(()=>deleteSpokenWord(p,'w2')).toThrow('neighbour');});
 it('never invents timing from subtitles',()=>{expect(parseTranscript('1\n00:00:01,000 --> 00:00:03,000\nHallo Welt')[0].words).toBeUndefined();expect(()=>deleteSpokenWord(fixture(),'unknown')).toThrow('untimed');});
 it('reads CrispASR millisecond offsets rather than centiseconds and shifts nested words',()=>{const [cue]=parseTranscript(JSON.stringify({transcription:[{offsets:{from:100,to:900},text:'Hallo',words:[{text:'Hallo',t0:10,t1:90,offsets:{from:100,to:900}}]}]}),4);expect(cue.start).toBe(4.1);expect(cue.words![0].end).toBe(4.9);});
 it('rejects unusable word boundaries',()=>{expect(()=>parseTranscript(JSON.stringify([{start:0,end:2,text:'Hi',words:[{start:1,end:0,text:'Hi'}]}]))).toThrow('word timestamps');});
});
