// Reproducible ESM adapter for libflacjs 5.6.0 (MIT wrapper / BSD libFLAC).
// Keep its environment configuration local: upstream patches the supplied fetch.
import {readFileSync,writeFileSync,copyFileSync} from 'node:fs';
const source=readFileSync('node_modules/libflacjs/dist/libflac.min.wasm.js','utf8');
const marker='function(global,expLib,require){';
const body=source.slice(source.indexOf(marker)+marker.length,source.lastIndexOf('});'));
writeFileSync('src/lib/flac/flac.mjs',`// Generated by scripts/vendor-flac.mjs; see LICENSE files in this directory.\nexport default function createFlac(wasmUrl) {\nconst global={FLAC_SCRIPT_LOCATION:{'libflac.min.wasm.wasm':wasmUrl},fetch:globalThis.fetch.bind(globalThis)};\nconst expLib=undefined, require=undefined;var Module={};\n${body}\n}\n`);
copyFileSync('node_modules/libflacjs/dist/libflac.min.wasm.wasm','src/lib/flac/flac.wasm');
copyFileSync('node_modules/libflacjs/LICENSE','src/lib/flac/LICENSE.wrapper');
