// ---------------------------------------------------------------------------
// CrispAudio — LicensesModal
// Third-party dependency licenses, generated by scripts/gen-licenses.mjs.
// ---------------------------------------------------------------------------

import { useTranslation } from 'react-i18next';
import { Modal } from './Modal';
import { useUIStore } from '../../stores/uiStore';
import { openExternal } from '../../lib/openExternal';
import licenses from '../../generated/licenses.json';

interface LicenseEntry {
  name: string;
  version: string;
  license: string;
  repository?: string;
  homepage?: string;
}

export function LicensesModal() {
  const { t } = useTranslation();
  const { activeModal, closeModal } = useUIStore();
  const entries = licenses as LicenseEntry[];

  return (
    <Modal
      isOpen={activeModal === 'licenses'}
      onClose={closeModal}
      title={t('licenses.title')}
      widthClass="max-w-lg"
    >
      <p className="text-xs text-gray-500 mb-3">{t('licenses.intro')}</p>
      <ul className="flex flex-col divide-y divide-gray-800">
        {entries.map((e) => {
          const link = e.repository ?? e.homepage;
          return (
            <li
              key={e.name}
              className="flex items-center justify-between gap-3 py-2"
            >
              <div className="min-w-0">
                {link ? (
                  <button
                    type="button"
                    onClick={() => openExternal(link)}
                    className="text-sm text-indigo-300 hover:text-indigo-200 transition-colors truncate block max-w-full text-left"
                    title={link}
                  >
                    {e.name}
                  </button>
                ) : (
                  <span className="text-sm text-gray-200 truncate block">
                    {e.name}
                  </span>
                )}
                <span className="text-xs text-gray-600">v{e.version}</span>
              </div>
              <span className="text-xs text-gray-400 whitespace-nowrap font-mono">
                {e.license}
              </span>
            </li>
          );
        })}
      </ul>
    </Modal>
  );
}
